#!/usr/bin/env python

import sys, re

regexp = r'[PROJECT_KEY]-[0-9]+(\W+|$)'
merge = r'Merge '

commit_msg_file = sys.argv[1]
with open(commit_msg_file) as file:
  content = file.read()
  correct = re.match(regexp, content)
  if not correct:
    print "Commit rejected: please include a Jira ticket number!"
    sys.exit(1)
  print "Commit approved."
  sys.exit(0)
